name: hello-node

on:
    push:
        # path:""
    workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
    
      - name: Setup Node.js
        run: 

      - name: Install dependencies
        run: echo ""

      - name: Eun Tests (If any)
        run: echo ""

  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
      - name: Checkout Code
        run: echo ""
    
      - name: Login to docker hub
        run: echo ""

      - name: Build and Push the Docker image
        run: echo ""




